package model.collections.plant;

public enum PlantFoodType
{
    NONE,
    SPAWN_SUN_ITEMS,
    PROJECTILE_BURST,
    SPAWN_CLONES,
    LOCAL_AOE_ATTACK,
    GRANT_PERMANENT_ARMOR,
    RANDOM_HYPNOTIZE,
    KNOCKBACK_BLAST,
    PULL_UNDERWATER,
    MAP_WIDE_FREEZE,
    MAP_WIDE_BUTTER,
    SELF_BOOST,
    INSTANT_KILL,
    LOBBER_BARRAGE,
    RANDOM_INSTANT_KILL,
    DISARM_BLAST,
    LANE_REDIRECT,
    PULL_AND_HEAL
}